package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"genos/gql/graph/generated"
	modelsGen "genos/gql/graph/models_gen"
	db "genos/infrastructure/sqlite"
	"genos/modules/orders/repository"
	"genos/modules/orders/usecase"
	"time"
)

// FindOrderByID is the resolver for the findOrderByID field.
func (r *entityResolver) FindOrderByID(ctx context.Context, id int64) (*modelsGen.Order, error) {
	uc := usecase.NewOrderUsecase(db.GetDatabaseConnection(), repository.NewOrderRepository(db.GetDatabaseConnection()))
	orderData, err := uc.GetOrder(ctx, uint64(id))
	if err != nil {
		return nil, err
	}
	return &modelsGen.Order{
		ID:            int64(orderData.ID),
		UserID:        int64(orderData.UserID),
		OrderNumber:   orderData.OrderNumber,
		TotalAmount:   orderData.TotalAmount,
		PaymentMethod: orderData.PaymentMethod,
		Status:        orderData.Status,
		CreatedAt:     orderData.CreatedAt,
		UpdatedAt:     orderData.UpdatedAt,
		OrderItems: func() []*modelsGen.OrderItem {
			items := make([]*modelsGen.OrderItem, len(orderData.OrderItems))
			for i := range orderData.OrderItems {
				item := orderData.OrderItems[i]
				items[i] = &modelsGen.OrderItem{
					ID:          int64(item.ID),
					OrderID:     int64(item.OrderID),
					ProductID:   int64(item.ProductID),
					ProductName: item.ProductName,
					Qty:         int(item.Qty),
					Price:       item.Price,
				}
			}
			return items
		}(),
	}, nil
}

// FindUserByID is the resolver for the findUserByID field.
func (r *entityResolver) FindUserByID(ctx context.Context, id int64) (*modelsGen.User, error) {
	uc := usecase.NewOrderUsecase(db.GetDatabaseConnection(), repository.NewOrderRepository(db.GetDatabaseConnection()))

	orderList, err := uc.GetOrderByUserID(ctx, uint64(id), nil)
	if err != nil {
		return nil, err
	}

	orders := make([]*modelsGen.Order, len(orderList))
	for i := range orderList {
		order := orderList[i]
		orders[i] = &modelsGen.Order{
			ID:            int64(order.ID),
			UserID:        int64(order.UserID),
			OrderNumber:   order.OrderNumber,
			TotalAmount:   order.TotalAmount,
			PaymentMethod: order.PaymentMethod,
			Status:        order.Status,
			CreatedAt:     order.CreatedAt,
			UpdatedAt:     order.UpdatedAt,
			DeletedAt: func() *time.Time {
				if order.DeletedAt.Valid {
					return &order.DeletedAt.Time
				}
				return nil
			}(),
		}

		orderItems := make([]*modelsGen.OrderItem, len(orderList[i].OrderItems))
		for j := range order.OrderItems {
			item := order.OrderItems[j]
			orderItems[j] = &modelsGen.OrderItem{
				ID:          int64(item.ID),
				OrderID:     int64(item.OrderID),
				ProductID:   int64(item.ProductID),
				ProductName: item.ProductName,
				Qty:         int(item.Qty),
				Price:       item.Price,
			}
		}
		orders[i].OrderItems = orderItems
	}

	return &modelsGen.User{
		ID:     id,
		Orders: orders,
	}, nil
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
