package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"genos/gql/graph/generated"
	modelsGen "genos/gql/graph/models_gen"
	db "genos/infrastructure/sqlite"
	models1 "genos/internal/common/models"
	"genos/modules/orders/models"
	"genos/modules/orders/repository"
	"genos/modules/orders/usecase"
)

// UserID is the resolver for the user_id field.
func (r *orderResolver) UserID(ctx context.Context, obj *models.Order) (int64, error) {
	if obj != nil {
		return int64(obj.UserID), nil
	}
	return 0, nil
}

// ProductID is the resolver for the product_id field.
func (r *orderItemResolver) ProductID(ctx context.Context, obj *models.OrderItem) (int64, error) {
	if obj != nil {
		return int64(obj.ProductID), nil
	}
	return 0, nil
}

// GetOrder is the resolver for the getOrder field.
func (r *queryResolver) GetOrder(ctx context.Context, id int64) (*modelsGen.ResponseOrder, error) {
	uc := usecase.NewOrderUsecase(db.GetDatabaseConnection(), repository.NewOrderRepository(db.GetDatabaseConnection()))
	orderData, err := uc.GetOrder(ctx, uint64(id))
	if err != nil {
		return nil, err
	}

	response := &modelsGen.ResponseOrder{
		Items: orderData,
	}

	return response, nil
}

// GetOrderByUserID is the resolver for the getOrderByUserId field.
func (r *queryResolver) GetOrderByUserID(ctx context.Context, option *models1.QueryOption) (*modelsGen.ResponseOrderList, error) {
	uc := usecase.NewOrderUsecase(db.GetDatabaseConnection(), repository.NewOrderRepository(db.GetDatabaseConnection()))
	orderList, err := uc.GetOrderList(ctx, option)
	if err != nil {
		return nil, err
	}

	orderItems := make([]*models.Order, len(orderList), 0)
	for i := range orderList {
		orderItems[i] = &orderList[i]
	}

	response := &modelsGen.ResponseOrderList{
		Items: orderItems,
	}
	return response, nil
}

// Order returns generated.OrderResolver implementation.
func (r *Resolver) Order() generated.OrderResolver { return &orderResolver{r} }

// OrderItem returns generated.OrderItemResolver implementation.
func (r *Resolver) OrderItem() generated.OrderItemResolver { return &orderItemResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type orderResolver struct{ *Resolver }
type orderItemResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *orderResolver) Items(ctx context.Context, obj *models.Order) ([]*models.OrderItem, error) {
	if obj != nil {
		orderItems := make([]*models.OrderItem, len(obj.OrderItems), 0)
		for i := range obj.OrderItems {
			orderItems[i] = &obj.OrderItems[i]
		}
		return orderItems, nil
	}
	return nil, nil
}
*/
