// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package modelsGen

import (
	models1 "genos/internal/common/models"
	"genos/modules/orders/models"
)

type Query struct {
}

type ResponseOrder struct {
	Items *models.Order `json:"items"`
}

type ResponseOrderList struct {
	Items      []*models.Order     `json:"items"`
	Pagination *models1.Pagination `json:"pagination"`
}
